name: redis-standalone

services:
  redis-master:
    image: redis:${REDIS_VERSION:-latest}
    hostname: redis-master
    container_name: redis-master
    ports:
      - ${REDIS_MASTER_PORT_EXTERNAL}:6379
    volumes:
      - ./data/redis-master:/data
    networks:
      - network

  redis-slave-1:
    image: redis:${REDIS_VERSION:-latest}
    container_name: redis-slave-1
    hostname: redis-slave-1
    ports:
      - ${REDIS_SLAVE_1_PORT_EXTERNAL}:6379
    environment:
      - REDIS_REPLICATION_MODE=slave
    depends_on:
      - redis-master
    command: ["sh", "-c", "redis-server --slaveof redis-master 6379"]
    networks:
      - network

  redis-slave-2:
    image: redis:${REDIS_VERSION:-latest}
    container_name: redis-slave-2
    hostname: redis-slave-2
    ports:
      - ${REDIS_SLAVE_2_PORT_EXTERNAL}:6379
    environment:
      - REDIS_REPLICATION_MODE=slave
    depends_on:
      - redis-master
    command: ["sh", "-c", "redis-server --slaveof redis-master 6379"]
    networks:
      - network

  redis-exporter:
    image: oliver006/redis_exporter:${REDIS_EXPORTER_VERSION:-latest}
    hostname: redis-exporter
    container_name: redis-exporter
    ports:
      - ${REDIS_EXPORTER_PORT_EXTERNAL}:9121
    environment:
      - REDIS_ADDR=
    networks:
      - network
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2

  redis-insight:
    image: redislabs/redisinsight:${REDIS_INSIGHT_VERSION:-latest}
    hostname: redis-insight
    container_name: redis-insight
    ports:
      - ${REDIS_INSIGHT_PORT_EXTERNAL}:5540
    networks:
      - network
    volumes:
      - ./data/redis-insight:/data

networks:
  network:
    driver: bridge