name: redis-standalone

services:
  redis:
    image: redis:${REDIS_VERSION:-latest}
    hostname: redis
    container_name: redis
    ports:
      - ${REDIS_PORT_EXTERNAL}:6379
    volumes:
      - ./data/redis:/data
    networks:
      - network

  redis-exporter:
    image: oliver006/redis_exporter:${REDIS_EXPORTER_VERSION:-latest}
    hostname: redis-exporter
    container_name: redis-exporter
    ports:
      - ${REDIS_EXPORTER_PORT_EXTERNAL}:9121
    environment:
      - REDIS_ADDR=redis://redis:6379
    networks:
      - network
    depends_on:
      - redis

  redis-insight:
    image: redislabs/redisinsight:${REDIS_INSIGHT_VERSION:-latest}
    hostname: redis-insight
    container_name: redis-insight
    ports:
      - ${REDIS_INSIGHT_PORT_EXTERNAL}:5540
    networks:
      - network
    volumes:
      - ./data/redis-insight:/data

networks:
  network:
    driver: bridge