global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: 'kafka'
    static_configs:
      - targets:
        - host.docker.internal:9991
        - host.docker.internal:9992
        - host.docker.internal:9993
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - host.docker.internal:9911
        - host.docker.internal:9912
        - host.docker.internal:9913
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://host.docker.internal:6381
        - redis://host.docker.internal:6382
        - redis://host.docker.internal:6383
        - redis://host.docker.internal:6384
        - redis://host.docker.internal:6385
        - redis://host.docker.internal:6386
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:9920
