global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: 'kafka'
    static_configs:
      - targets: ['host.docker.internal:9991','host.docker.internal:9992','host.docker.internal:9993']