name: postgres-simple

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    hostname: postgres
    container_name: postgres
    networks:
      - network
    ports:
      - ${POSTGRES_PORT_EXTERNAL}:5432
    volumes:
      - ./volumes/postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

networks:
  network:
    driver: bridge