name: kafka

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${ZOOKEPER_VERSION:-latest}
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEPER_PORT:-2181}
    ports:
      - ${ZOOKEPER_PORT:-2181}:${ZOOKEPER_PORT:-2181}
    networks:
      - network

  kafka-broker-1:
    image: confluentinc/cp-kafka:${KAFKA_BROKER_VERSION:-latest}
    hostname: kafka-broker-1
    container_name: kafka-broker-1
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_BROKER_1_PORT_EXTERNAL}:${KAFKA_BROKER_1_PORT_EXTERNAL}
      - ${KAFKA_BROKER_1_METRICS_PORT_EXTERNAL}:${KAFKA_BROKER_METRICS_PORT_INTERNAL:-9990}
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_1_ID:-1}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEPER_PORT:-2181}
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-1:${KAFKA_BROKER_PORT_INTERNAL:-9090},EXTERNAL://localhost:${KAFKA_BROKER_1_PORT_EXTERNAL}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-1.3.0.jar=${KAFKA_BROKER_METRICS_PORT_INTERNAL:-9990}:/usr/share/jmx_exporter/kafka-broker.yml
    volumes:
      - ./jmx-exporter:/usr/share/jmx_exporter/
    networks:
      - network

  kafka-broker-2:
    image: confluentinc/cp-kafka:${KAFKA_BROKER_VERSION:-latest}
    hostname: kafka-broker-2
    container_name: kafka-broker-2
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_BROKER_2_PORT_EXTERNAL}:${KAFKA_BROKER_2_PORT_EXTERNAL}
      - ${KAFKA_BROKER_2_METRICS_PORT_EXTERNAL}:${KAFKA_BROKER_METRICS_PORT_INTERNAL:-9990}
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_2_ID:-2}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEPER_PORT:-2181}
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-2:${KAFKA_BROKER_PORT_INTERNAL:-9090},EXTERNAL://localhost:${KAFKA_BROKER_2_PORT_EXTERNAL}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-1.3.0.jar=${KAFKA_BROKER_METRICS_PORT_INTERNAL:-9990}:/usr/share/jmx_exporter/kafka-broker.yml
    volumes:
      - ./jmx-exporter:/usr/share/jmx_exporter/
    networks:
      - network

  kafka-broker-3:
    image: confluentinc/cp-kafka:${KAFKA_BROKER_VERSION:-latest}
    hostname: kafka-broker-3
    container_name: kafka-broker-3
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_BROKER_3_PORT_EXTERNAL}:${KAFKA_BROKER_3_PORT_EXTERNAL}
      - ${KAFKA_BROKER_3_METRICS_PORT_EXTERNAL}:${KAFKA_BROKER_METRICS_PORT_INTERNAL:-9990}
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_3_ID:-3}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEPER_PORT:-2181}
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker-3:${KAFKA_BROKER_PORT_INTERNAL:-9090},EXTERNAL://localhost:${KAFKA_BROKER_3_PORT_EXTERNAL}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-1.3.0.jar=${KAFKA_BROKER_METRICS_PORT_INTERNAL:-9990}:/usr/share/jmx_exporter/kafka-broker.yml
    volumes:
      - ./jmx-exporter:/usr/share/jmx_exporter/
    networks:
      - network

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:${KAFKA_UI_VERSION:-latest}
    hostname: kafka-ui
    ports:
      - ${KAFKA_UI_PORT_EXTERNAL}:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_UI_CLUSTER_0_NAME}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker-1:${KAFKA_BROKER_PORT_INTERNAL:-9090},kafka-broker-2:${KAFKA_BROKER_PORT_INTERNAL:-9090},kafka-broker-3:${KAFKA_BROKER_PORT_INTERNAL:-9090}
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:${ZOOKEPER_PORT:-2181}
      DYNAMIC_CONFIG_ENABLED: true
    networks:
      - network

networks:
  network:
    driver: bridge